// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace RxUISimpleTimer.Mac.ViewControllers
{
    public partial class HistoryViewController : NSViewController
    {
        public HistoryViewController(IntPtr handle)
            : base(handle)
        {
        }
    }
}
