// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using ReactiveUI;
using RxUISimpleTimer.Core.ViewModels;

namespace RxUISimpleTimer.Mac.ViewControllers
{
    public partial class OperationViewController : NSViewController, IViewFor<OperationViewModel>
    {
        public OperationViewController(IntPtr handle)
            : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            VM = new OperationViewModel();
        }

        private OperationViewModel VM;

        #region IViewFor implementation

        OperationViewModel IViewFor<OperationViewModel>.ViewModel
        {
            get
            {
                return VM;
            }
            set
            {
                VM = value;
            }
        }

        #endregion

        #region IViewFor implementation

        object IViewFor.ViewModel
        {
            get
            {
                return VM;  
            }
            set
            {
                VM = (OperationViewModel)value;
            }
        }

        #endregion
    }
}
