// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using RxUISimpleTimer.Mac.ViewControllers;
using System.Diagnostics;

namespace RxUISimpleTimer.Mac
{
    public partial class MainWindowController : NSWindowController
    {
        public MainWindowController(IntPtr handle)
            : base(handle)
        {
        }

        partial void ShowHistoryBar(NSObject sender)
        {
            var vc = this.ContentViewController as MainViewController;
            if (vc == null)
            {
                Debug.WriteLine("ViewController was null.");
                return;
            }

            vc.HistoryView.Collapsed = !vc.HistoryView.Collapsed;
        }
    }
}
